#!/usr/bin/env bash
# Regenerate the committed Temporal worked-example workflow artefact
# from the canonical CACAO playbook. Run from the repo root after any
# change to the playbook source or to compilers/temporal/*.
#
# The disclosure-timeline-record snapshot is regenerated by the sibling
# ``regenerate.py`` script in this directory; that artifact targets
# the Temporal activity adapter for the per-finding evidence record
# rather than the whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON="${REPO_ROOT}/content/playbooks/codebase_vuln_management/playbook.cacao.json"

# Keep the mirrored CACAO source byte-identical to the canonical playbook.
cp "${CANON}" "${HERE}/playbook.cacao.json"

# Emit the Temporal workflow stub from the canonical playbook via the
# unified CLI.
PYTHONPATH="${REPO_ROOT}" python -m tools.compile \
    "${CANON}" \
    --target temporal \
    --out "${HERE}/workflow.temporal.py"
