#!/usr/bin/env bash
# Regenerate the committed n8n worked-example workflow artefact from
# the canonical CACAO playbook. Run from the repo root after any
# change to the playbook source or to compilers/n8n/*.
#
# The per-execution access-evidence artefact under ``evidence/`` is
# regenerated by the sibling ``regenerate.py`` script in this
# directory; that artefact targets the n8n adapter for the F-CP-07
# access stream rather than the whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON="${REPO_ROOT}/content/playbooks/iam-auditor/playbook.cacao.json"

# Keep the mirrored CACAO source byte-identical to the canonical playbook.
cp "${CANON}" "${HERE}/playbook.cacao.json"

# Emit the n8n workflow from the canonical playbook via the unified CLI.
PYTHONPATH="${REPO_ROOT}" python -m tools.compile \
    "${CANON}" \
    --target n8n \
    --out "${HERE}/workflow.n8n.json"
