#!/usr/bin/env bash
# Top-level orchestrator: regenerate (or check) the committed worked-example
# artefacts that ship under examples/{n8n,temporal,langgraph}/<workflow>/.
#
# Usage:
#   ./regenerate.sh                       # regenerate every example
#   ./regenerate.sh <target>              # regenerate every example for one target
#   ./regenerate.sh <target> <workflow>   # regenerate a single example
#   ./regenerate.sh --check               # dry-run: regenerate, diff against
#                                         # committed bytes, restore on drift,
#                                         # exit non-zero if anything drifted
#   ./regenerate.sh --check <target> [<workflow>]
#
# --check is intended for CI. It writes regenerated bytes into the working
# tree, compares them against HEAD with `git diff`, then restores the committed
# bytes with `git checkout --` so the worktree is left clean either way.
# On drift it prints a contributor-friendly message naming the exact command
# to run locally.
#
# Each per-example regenerate.sh is the source of truth for *how* that
# example is built. This script only orchestrates discovery + drift detection.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
cd "${HERE}"

CHECK=0
TARGET=""
WORKFLOW=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --check)
            CHECK=1
            shift
            ;;
        -h|--help)
            sed -n '2,18p' "$0"
            exit 0
            ;;
        --)
            shift
            break
            ;;
        -*)
            echo "regenerate.sh: unknown flag: $1" >&2
            exit 2
            ;;
        *)
            if [[ -z "${TARGET}" ]]; then
                TARGET="$1"
            elif [[ -z "${WORKFLOW}" ]]; then
                WORKFLOW="$1"
            else
                echo "regenerate.sh: unexpected positional argument: $1" >&2
                exit 2
            fi
            shift
            ;;
    esac
done

# ---------------------------------------------------------------------------
# Discover (target, workflow) pairs that have a per-example regenerate.sh.
# ---------------------------------------------------------------------------
declare -a PAIRS=()
for target_dir in examples/n8n examples/temporal examples/langgraph; do
    target_name="$(basename "${target_dir}")"
    if [[ -n "${TARGET}" && "${target_name}" != "${TARGET}" ]]; then
        continue
    fi
    [[ -d "${target_dir}" ]] || continue
    for example_dir in "${target_dir}"/*/; do
        [[ -d "${example_dir}" ]] || continue
        wf_name="$(basename "${example_dir}")"
        if [[ -n "${WORKFLOW}" && "${wf_name}" != "${WORKFLOW}" ]]; then
            continue
        fi
        if [[ -x "${example_dir}regenerate.sh" || -f "${example_dir}regenerate.sh" ]]; then
            PAIRS+=("${target_name}/${wf_name}")
        fi
    done
done

if [[ ${#PAIRS[@]} -eq 0 ]]; then
    echo "regenerate.sh: no matching examples found" >&2
    [[ -n "${TARGET}" || -n "${WORKFLOW}" ]] && exit 2
    exit 0
fi

# ---------------------------------------------------------------------------
# Drift accumulator (--check only).
# ---------------------------------------------------------------------------
DRIFTED=()

for pair in "${PAIRS[@]}"; do
    target_name="${pair%%/*}"
    wf_name="${pair##*/}"
    example_dir="examples/${target_name}/${wf_name}"
    script="${example_dir}/regenerate.sh"

    if [[ ${CHECK} -eq 1 ]]; then
        echo "[check] ${pair}"
    else
        echo "[regen] ${pair}"
    fi

    # Each per-example script expects to be runnable from anywhere (it
    # cd's via its own HERE), so just exec it directly.
    bash "${script}"

    if [[ ${CHECK} -eq 1 ]]; then
        # Compare regenerated bytes against the committed bytes for this
        # example's directory. `git diff --exit-code` returns 1 on drift.
        if ! git diff --quiet -- "${example_dir}"; then
            echo "BYTE-PARITY DRIFT in ${target_name}/${wf_name} — run: ./regenerate.sh ${target_name} ${wf_name}"
            DRIFTED+=("${pair}")
        fi
        # Always restore the committed bytes so the worktree stays clean,
        # regardless of whether drift was detected.
        git checkout -- "${example_dir}" >/dev/null 2>&1 || true
    fi
done

if [[ ${CHECK} -eq 1 && ${#DRIFTED[@]} -gt 0 ]]; then
    echo
    echo "regenerate.sh --check: drift detected in ${#DRIFTED[@]} example(s):"
    for pair in "${DRIFTED[@]}"; do
        echo "  - ${pair}"
    done
    echo
    echo "To resolve: run ./regenerate.sh <target> <workflow> locally and commit the result."
    exit 1
fi

exit 0
