#!/usr/bin/env bash
# Regenerate the committed detection_engineering LangGraph worked-example
# artefacts from the canonical CACAO playbook. Run from the repo root
# after any change to the playbook source or to compilers/langgraph/*.
#
# The rule-effectiveness snapshot is regenerated by the sibling
# ``regenerate.py`` script in this directory; that artefact targets the
# LangGraph node adapter for the per-rule-version snapshot rather than
# the whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON_YAML="${REPO_ROOT}/content/playbooks/detection_engineering/playbook.cacao.yaml"
MIRROR_JSON="${HERE}/playbook.cacao.json"

# Mirror the canonical CACAO YAML into a byte-deterministic JSON form
# (sorted keys, 2-space indent, trailing newline) — the LangGraph
# emitter consumes JSON via the CACAO parser; the two formats
# round-trip through ``yaml.safe_load`` + ``json.dumps`` and the schema
# is format-agnostic.
PYTHONPATH="${REPO_ROOT}" python -c "
import json
from pathlib import Path
import yaml
src = Path('${CANON_YAML}')
dst = Path('${MIRROR_JSON}')
data = yaml.safe_load(src.read_text(encoding='utf-8'))
dst.write_text(json.dumps(data, indent=2, sort_keys=True) + '\n', encoding='utf-8')
"

# Emit GraphSpec + generated state bindings from the JSON mirror.
PYTHONPATH="${REPO_ROOT}" python -m compilers.langgraph.emit  "${MIRROR_JSON}" > "${HERE}/graph_spec.json"
PYTHONPATH="${REPO_ROOT}" python -m compilers.langgraph.state "${MIRROR_JSON}" > "${HERE}/state_bindings.py"

# Materialise the dependency-free audit-mirror sibling. See
# docs/observability/audit-mirror.md for the co-location rationale.
PYTHONPATH="${REPO_ROOT}" python -m compilers._shared.audit_mirror_cli \
    --out "${HERE}/_audit_mirror.py"
