#!/usr/bin/env bash
# Regenerate the committed Temporal worked-example artefacts for the
# contractual-obligations-tracker workflow from the canonical CACAO
# playbook. Run from the repo root after any change to the playbook
# source, the Temporal compiler, or the Temporal contractual-obligations
# activity adapter.
#
# The per-execution obligation-evidence artefact is regenerated by the
# sibling ``regenerate.py`` script in this directory; that artifact
# targets the Temporal contractual-obligations activity for the
# representative evidence record rather than the whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON="${REPO_ROOT}/content/playbooks/contractual_obligations_tracker/playbook.cacao.json"

# Keep the mirrored CACAO source byte-identical to the canonical playbook.
cp "${CANON}" "${HERE}/playbook.cacao.json"

# Emit the Temporal workflow stub from the canonical playbook via the
# unified CLI.
PYTHONPATH="${REPO_ROOT}" python -m tools.compile \
    "${CANON}" \
    --target temporal \
    --out "${HERE}/workflow.temporal.py"

# Materialise the representative obligation-evidence artefact under
# evidence/ via the Temporal contractual-obligations activity adapter.
PYTHONPATH="${REPO_ROOT}" python "${HERE}/regenerate.py"
