"""Helper-call-site tests for the langgraph emitter (F-CR-04 CORE-LG-EMITTER).

These tests pin the wiring between :mod:`compilers.langgraph.state`'s emitted
``@tool`` bodies and the audit-trail mirror helper they call:

- The emitted source for every CACAO action / playbook-action step opens an
  OpenTelemetry span and appends an :class:`AuditRecord` to the surrounding
  trail inside it.
- The recorded attribute set carries the envelope contract: stable
  ``secops_ng.playbook.id`` / ``secops_ng.step.id`` / ``secops_ng.tool.name``
  keys plus the empty-string ``secops_ng.workflow.run_id`` compile-time
  placeholder (per Director's 2026-06-03 decision baked into the
  CORE-LG-EMITTER card body).
- No ``secops_ng.audit.ts`` attribute is emitted — timestamps remain runtime
  concerns surfaced via OTel spans.
- Replaying the same input is a no-op at the trail level (idempotency).
- The sovereign-stack guard holds: only ``opentelemetry`` is imported by the
  emitted source — no vendor SDK substrings, no hard-coded OTLP endpoint.

The tests deliberately *do not* compare against the committed goldens — the
goldens are stale on this PR and get regenerated by the CORE-LG-GOLDENS
sibling. Instead they ad-hoc compile-and-import the emitted source from a
synthetic playbook against a freshly-materialised ``_audit_mirror.py`` so the
helper call site itself is exercised end to end without depending on the
golden suite.
"""
from __future__ import annotations

import ast
import asyncio
import importlib
import sys
from pathlib import Path

import pytest

from compilers._shared.cacao_parser import parse
from compilers._shared.observability import (
    SPAN_ATTR_PLAYBOOK_ID,
    SPAN_ATTR_STEP_ID,
    SPAN_ATTR_TOOL_NAME,
    SPAN_ATTR_WORKFLOW_RUN_ID,
    render_audit_mirror_module,
)
from compilers.langgraph.state import (
    render_module,
    render_tool_bindings,
    tool_bindings,
)


_PB_ID = "playbook--ffffffff-ffff-4fff-8fff-ffffffffffff"
_START = "start--11111111-1111-4111-8111-111111111111"
_ACTION = "action--22222222-2222-4222-8222-222222222222"
_END = "end--33333333-3333-4333-8333-333333333333"


def _synthetic_playbook() -> dict:
    """Minimal playbook with one action step — enough to exercise the wiring."""
    return {
        "type": "playbook",
        "spec_version": "2.0",
        "id": _PB_ID,
        "name": "audit-mirror emitter test",
        "playbook_types": ["investigation"],
        "created_by": "identity--aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa",
        "created": "2026-06-03T00:00:00Z",
        "modified": "2026-06-03T00:00:00Z",
        "playbook_variables": {
            "__finding_id__": {"type": "string", "external": True},
        },
        "workflow_start": _START,
        "workflow": {
            _START: {
                "type": "start",
                "name": "begin",
                "on_completion": _ACTION,
            },
            _ACTION: {
                "type": "action",
                "name": "enrich finding",
                "in_args": ["__finding_id__"],
                "on_completion": _END,
            },
            _END: {"type": "end", "name": "done"},
        },
        "x_secops_ng": {
            "stable_id": "playbook.emitter_audit_test@v1",
            "content_version": "0.1.0",
            "maturity": "draft",
        },
    }


# --------------------------------------------------------------------------- #
# Static-source assertions — exercise the @tool emission shape directly.       #
# --------------------------------------------------------------------------- #


def test_emitted_tool_body_calls_audit_trail_append() -> None:
    """The emitted @tool body must call ``AuditTrail.current().append(...)``."""
    src = render_tool_bindings(tool_bindings(parse(_synthetic_playbook())))
    assert "AuditTrail.current().append(" in src
    assert "AuditRecord(span_name=" in src


def test_emitted_tool_attributes_include_workflow_run_id_placeholder() -> None:
    """Envelope contract: empty-string ``secops_ng.workflow.run_id`` is emitted."""
    src = render_tool_bindings(tool_bindings(parse(_synthetic_playbook())))
    # ``_py_repr`` uses ``repr`` so the attribute key and value render as
    # single-quoted Python literals.
    assert f"'{SPAN_ATTR_WORKFLOW_RUN_ID}': ''" in src


def test_emitted_tool_attributes_omit_timestamp() -> None:
    """No ``secops_ng.audit.ts`` attribute: timestamps stay runtime-only."""
    src = render_tool_bindings(tool_bindings(parse(_synthetic_playbook())))
    assert "secops_ng.audit.ts" not in src


def test_emitted_module_only_imports_opentelemetry_for_otel() -> None:
    """Sovereign-stack guard: only ``opentelemetry.*`` imports, no vendor SDK."""
    src = render_module(parse(_synthetic_playbook()))
    tree = ast.parse(src)
    otel_imports: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.ImportFrom) and node.module:
            if node.module.startswith("opentelemetry"):
                otel_imports.append(node.module)
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("opentelemetry"):
                    otel_imports.append(alias.name)
    # At least one OTel import (the rendered ``from opentelemetry import trace``).
    assert any("opentelemetry" in m for m in otel_imports)
    # Vendor SDK substrings the linter would flag — none in emitted source.
    for forbidden in ("datadog", "newrelic", "elastic_apm", "dynatrace", "honeycomb"):
        assert forbidden not in src.lower()
    # No hard-coded OTLP endpoint URL.
    assert "http://" not in src
    assert "https://" not in src


# --------------------------------------------------------------------------- #
# Live-import assertions — wire the emitted source up against a real          #
# _audit_mirror.py sibling and exercise the helper call site at runtime.       #
# --------------------------------------------------------------------------- #


def _materialise_emitted_pkg(tmp_path: Path, name: str, playbook: dict):
    """Drop the emitted ``state_bindings.py`` + a fresh ``_audit_mirror.py``
    into a tmp package so the relative ``from ._audit_mirror import ...`` in
    the emitted source resolves cleanly."""
    pkg = tmp_path / name
    pkg.mkdir()
    (pkg / "__init__.py").write_text("", encoding="utf-8")
    (pkg / "_audit_mirror.py").write_text(render_audit_mirror_module(), encoding="utf-8")
    (pkg / "state_bindings.py").write_text(
        render_module(parse(playbook)), encoding="utf-8"
    )
    sys.path.insert(0, str(tmp_path))
    return importlib.import_module(f"{name}.state_bindings"), importlib.import_module(
        f"{name}._audit_mirror"
    )


@pytest.fixture
def emitted_modules(tmp_path: Path):
    name = "lg_emitter_audit_pkg"
    bindings_mod, mirror_mod = _materialise_emitted_pkg(
        tmp_path, name, _synthetic_playbook()
    )
    yield bindings_mod, mirror_mod
    sys.path.remove(str(tmp_path))
    for mod_name in (
        f"{name}.state_bindings",
        f"{name}._audit_mirror",
        name,
    ):
        sys.modules.pop(mod_name, None)


def _drive_emitted_coro(bindings_mod, mirror_mod, *, replays: int = 1):
    """Run the emitted ``enrich_finding`` coroutine N times and capture the
    audit trail snapshot from inside the same asyncio task — so the
    ContextVar binding the emitted code wrote is the one we read.

    The emitted body raises :class:`NotImplementedError` after the
    ``AuditTrail.current().append(...)`` call, so the helper invocation is
    observable even though the stub body is a deliberate ``NotImplementedError``.
    """
    tool_obj = bindings_mod.enrich_finding

    async def _runner():
        # The @tool decoration exposes the underlying coroutine on
        # ``.coroutine``; calling it directly keeps us in the current asyncio
        # task context so the ContextVar set by ``AuditTrail.current()``
        # inside the emitted body is visible when we snapshot below.
        for _ in range(replays):
            try:
                await tool_obj.coroutine(finding_id="f-1")
            except NotImplementedError:
                pass
        return mirror_mod.AuditTrail.current().snapshot()

    return asyncio.run(_runner())


def test_invoking_emitted_tool_appends_audit_record(emitted_modules) -> None:
    """Driving the emitted @tool stub appends one record with the bound envelope."""
    bindings_mod, mirror_mod = emitted_modules
    snap = _drive_emitted_coro(bindings_mod, mirror_mod)
    assert len(snap) == 1
    record = snap[0]
    assert record.span_name == f"tool.{_ACTION}"
    attrs = dict(record.attributes)
    assert attrs[SPAN_ATTR_PLAYBOOK_ID] == _PB_ID
    assert attrs[SPAN_ATTR_STEP_ID] == _ACTION
    assert attrs[SPAN_ATTR_TOOL_NAME] == "enrich_finding"
    # Envelope contract: empty-string placeholder, NO ts attribute.
    assert attrs[SPAN_ATTR_WORKFLOW_RUN_ID] == ""
    assert "secops_ng.audit.ts" not in attrs


def test_replaying_emitted_tool_is_idempotent(emitted_modules) -> None:
    """Re-driving the emitted @tool stub does not duplicate the audit row."""
    bindings_mod, mirror_mod = emitted_modules
    snap = _drive_emitted_coro(bindings_mod, mirror_mod, replays=3)
    assert len(snap) == 1, f"replay duplicated audit rows: snapshot size {len(snap)}"
