#!/usr/bin/env bash
# Regenerate the committed n8n worked-example artefacts for the
# onboarding/offboarding-tracker workflow from the canonical CACAO
# playbook. Run from the repo root after any change to the playbook
# source, the n8n compiler, or the onboarding/offboarding primitives.
#
# The per-execution access-evidence artefact under ``evidence/`` is
# regenerated by the sibling ``regenerate.py`` script in this
# directory; that artefact targets the n8n access-evidence adapter
# (reused F-CP-07 stream) rather than the whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON="${REPO_ROOT}/content/playbooks/onboarding_offboarding_tracker/playbook.cacao.json"

# Keep the mirrored CACAO source byte-identical to the canonical playbook.
cp "${CANON}" "${HERE}/playbook.cacao.json"

# Emit the n8n workflow from the canonical playbook via the unified CLI.
PYTHONPATH="${REPO_ROOT}" python -m tools.compile \
    "${CANON}" \
    --target n8n \
    --out "${HERE}/workflow.n8n.json"

# Materialise the representative access-evidence artefact under
# evidence/ via the n8n access-evidence adapter.
PYTHONPATH="${REPO_ROOT}" python "${HERE}/regenerate.py"
