"""State TypedDict and ``@tool`` bindings for the vuln-intake worked example.

TBD: regenerated by the LangGraph reference compiler from
``playbook.cacao.json``. Stub kept for scaffolding only.
"""

# TBD: regenerated by CORE
