#!/usr/bin/env bash
# Regenerate the committed n8n worked-example workflow artefact from
# the canonical CACAO playbook. Run from the repo root after any
# change to the playbook source or to compilers/n8n/*.
#
# The rule-effectiveness snapshot is regenerated by the sibling
# ``regenerate.py`` script in this directory; that artifact targets
# the n8n adapter for the per-rule-version snapshot rather than the
# whole workflow graph.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "${HERE}/../../.." && pwd)"
CANON="${REPO_ROOT}/content/playbooks/detection-engineering/playbook.cacao.yaml"

# Emit the n8n workflow from the canonical playbook via the unified CLI.
# The CLI accepts YAML or JSON; the detection-engineering source ships
# as YAML so it can carry inline comments alongside the schema-valid
# document the parser consumes.
PYTHONPATH="${REPO_ROOT}" python -m tools.compile \
    "${CANON}" \
    --target n8n \
    --out "${HERE}/workflow.n8n.json"
