#!/usr/bin/env python3
"""Render a public-facing kanban status view from the local Hermes board.

This script does **not** touch ``ROADMAP.md`` — that document is the
hand-curated source of truth, edited via PRs. This renderer produces
``docs/kanban-status.md``: the live, per-card status of work in the
public lanes, regenerated on cadence.

A card is included only if it is explicitly cleared for public exposure:

  1. Its body contains the literal marker ``<public-roadmap/>``, OR
  2. Its body or title references a repository on the
     ``WILL_BE_PUBLIC_REPOS`` allow-list (e.g. ``secops-ng-framework``,
     ``secops-ng-website``).

All other cards are excluded. The renderer never emits card bodies — only
the title and status of eligible cards — to keep accidental private
context out of the output.

Usage:
    python scripts/render_roadmap.py [--db PATH] [--out PATH]

The database path defaults to ``$HERMES_KANBAN_DB`` if set, otherwise
``~/.hermes/kanban/boards/secops-ng/kanban.db``. The output path defaults
to ``docs/kanban-status.md``.
"""
from __future__ import annotations

import argparse
import os
import re
import sqlite3
import sys
from datetime import datetime, timezone
from pathlib import Path

PUBLIC_MARKER = "<public-roadmap/>"

WILL_BE_PUBLIC_REPOS = (
    "secops-ng-framework",
    "secops-ng-website",
)

STATUS_ORDER = ("todo", "in_progress", "running", "blocked", "done")

STATUS_HEADINGS = {
    "todo": "Up Next",
    "in_progress": "In Progress",
    "running": "In Progress",
    "blocked": "Blocked",
    "done": "Shipped",
}


def default_db_path() -> Path:
    env = os.environ.get("HERMES_KANBAN_DB")
    if env:
        return Path(env)
    return Path.home() / ".hermes" / "kanban" / "boards" / "secops-ng" / "kanban.db"


def is_public_card(title: str, body: str) -> bool:
    """Return True iff a card is cleared for public exposure."""
    if PUBLIC_MARKER in (body or ""):
        return True
    haystack = f"{title or ''}\n{body or ''}"
    for repo in WILL_BE_PUBLIC_REPOS:
        if re.search(rf"\b{re.escape(repo)}\b", haystack):
            return True
    return False


def load_public_cards(db_path: Path) -> dict[str, list[tuple[str, str]]]:
    """Return ``{display_status: [(id, title), ...]}`` for public cards."""
    if not db_path.exists():
        raise SystemExit(f"kanban db not found: {db_path}")
    conn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        rows = conn.execute(
            "SELECT id, title, status, body FROM tasks WHERE status IN ({}) "
            "ORDER BY priority DESC, created_at ASC".format(
                ",".join("?" * len(STATUS_ORDER))
            ),
            STATUS_ORDER,
        ).fetchall()
    finally:
        conn.close()

    buckets: dict[str, list[tuple[str, str]]] = {
        STATUS_HEADINGS[s]: [] for s in STATUS_ORDER
    }
    for tid, title, status, body in rows:
        if not is_public_card(title or "", body or ""):
            continue
        heading = STATUS_HEADINGS.get(status)
        if heading is None:
            continue
        clean_title = (title or "").replace(PUBLIC_MARKER, "").strip()
        buckets[heading].append((tid, clean_title))
    return buckets


def render(buckets: dict[str, list[tuple[str, str]]]) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines: list[str] = []
    lines.append("# SecOps-NG — Kanban Status")
    lines.append("")
    lines.append(
        "_Auto-generated by `scripts/render_roadmap.py` from the local "
        "Hermes kanban board. Only cards explicitly cleared for public "
        "exposure (via `<public-roadmap/>` marker or a will-be-public "
        "repo reference) appear here._"
    )
    lines.append("")
    lines.append(
        "_This is a live status view, not the roadmap. For the "
        "hand-curated source-of-truth feature definitions, see "
        "[`../ROADMAP.md`](../ROADMAP.md)._"
    )
    lines.append("")
    lines.append(f"_Last rendered: {now}_")
    lines.append("")
    seen: set[str] = set()
    for status in STATUS_ORDER:
        heading = STATUS_HEADINGS[status]
        if heading in seen:
            continue
        seen.add(heading)
        items = buckets.get(heading, [])
        lines.append(f"## {heading}")
        lines.append("")
        if not items:
            lines.append("_No public cards in this lane._")
        else:
            for _tid, title in items:
                lines.append(f"- {title}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--db",
        type=Path,
        default=default_db_path(),
        help="path to the Hermes kanban sqlite database",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parent.parent / "docs" / "kanban-status.md",
        help="output kanban-status markdown path",
    )
    args = parser.parse_args(argv)

    buckets = load_public_cards(args.db)
    args.out.write_text(render(buckets), encoding="utf-8")
    total = sum(len(v) for v in buckets.values())
    print(f"wrote {args.out} ({total} public cards across {len(buckets)} lanes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
