"""Render the family-grouped playbook table into content/playbooks/README.md.

The README carries a full table of playbooks so a newcomer can survey the
catalogue without running anything — but hand-maintained tables in that file
have drifted every time one existed (one revision listed six playbooks while
the tree held forty-seven). So the table is *generated*: this module rewrites
the block between the two marker comments, and a test fails whenever the
committed README no longer matches a fresh render.

Usage:
    python -m tools.render_playbook_table            # rewrite the README block
    python -m tools.render_playbook_table --check    # exit 1 if stale

Classification is deliberate, not clever: a slug prefixed by a regulation
(``dora_``, ``nis2_``, ``cra_``, ``eu_ai_act_``, ``eidas2_``) files under
*Regulatory programmes* automatically; every other slug must appear in
``FAMILIES`` below. An unknown slug lands in *Unfiled* and the test suite
rejects it, so adding a playbook forces a one-line classification here rather
than silently growing an uncategorised tail.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
PLAYBOOK_DIR = REPO_ROOT / "content" / "playbooks"
README = PLAYBOOK_DIR / "README.md"

BEGIN = "<!-- playbook-table:begin — generated by tools/render_playbook_table.py; do not hand-edit -->"
END = "<!-- playbook-table:end -->"

# Slugs with one of these prefixes classify themselves: the prefix names the
# regulation the playbook serves, which is the family. Everything else needs
# an explicit entry below.
REGULATION_PREFIXES = ("dora_", "nis2_", "cra_", "eu_ai_act_", "eidas2_")
REGULATORY_FAMILY = "Regulatory programmes"

# Ordered: this is the order families render in. Within a family, slugs
# render alphabetically regardless of the order written here.
FAMILIES: dict[str, tuple[str, ...]] = {
    "Alert & incident lifecycle": (
        "alert_triage",
        "incident_management",
        "post_incident_review",
    ),
    "Scenario response": (
        "agentic_threat_response",
        "cloud_misconfiguration",
        "data_exfil",
        "ddos_response",
        "identity_compromise",
        "phishing_triage",
        "ransomware_containment",
    ),
    "Vulnerability lifecycle": (
        "codebase_vuln_management",
        "patch_management",
        "vuln_intake",
        "vulnerability_management",
    ),
    "Threat intel & detection engineering": (
        "detection_engineering",
        "threat_intel_ingest",
    ),
    "Identity & access": (
        "iam_auditor",
        "mfa_secured_comms",
        "onboarding_offboarding_tracker",
    ),
    "Posture & asset management": (
        "asset_management",
        "crypto_posture_management",
        "cryptographic_controls",
        "infra_posture_management",
        "network_security",
    ),
    "Supply chain & contracts": (
        "contractual_obligations_tracker",
        "supply_chain_security",
    ),
    "Resilience & continuity": (
        "backup_recovery",
        "business_continuity",
    ),
    "Privacy & data protection": (
        "data_protection_impact_assessment",
        "data_subject_rights",
    ),
    "SOC operations & programme": (
        "ai_human_oversight",
        "cyber_hygiene_training",
        "executive_metrics",
        "it_security_support_agent",
        "on_call_rotation",
        "security_awareness_training",
    ),
    # Regulation-prefixed slugs (dora_, nis2_, cra_, eu_ai_act_, eidas2_) are
    # appended here automatically. soc2_evidence_collector is listed explicitly
    # because its slug names the artifact rather than the regime — it scores
    # coverage against the AICPA Trust Services Criteria, which makes it a
    # regulatory-programme playbook despite carrying no regime prefix.
    REGULATORY_FAMILY: ("soc2_evidence_collector",),
}

UNFILED = "Unfiled"


def collect_sources() -> dict[str, Path]:
    """Slug -> canonical source, across all three committed layouts.

    Prefers the in-directory form when a slug is reachable twice (the
    alert_triage dual layout). Skips ``_``-prefixed scaffolding.
    """
    out: dict[str, Path] = {}
    for pattern in ("*/playbook.cacao.json", "*/playbook.cacao.yaml"):
        for p in sorted(PLAYBOOK_DIR.glob(pattern)):
            slug = p.parent.name
            if not slug.startswith("_") and slug not in out:
                out[slug] = p
    for p in sorted(PLAYBOOK_DIR.glob("*.cacao.yaml")):
        slug = p.name.removesuffix(".cacao.yaml")
        if not slug.startswith("_") and slug not in out:
            out[slug] = p
    return out


def _load(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    if path.suffix == ".yaml":
        import yaml  # declared dep (pyyaml>=6.0)

        return yaml.safe_load(text) or {}
    return json.loads(text)


def short_description(doc: dict) -> str:
    """First sentence of the CACAO description, faithfully.

    Only the decorative ``SKELETON — `` prefix is stripped; the words that
    remain are the author's. Truncation is marked, never silent.
    """
    desc = (doc.get("description") or "").strip()
    for prefix in ("SKELETON — ", "SKELETON —", "SKELETON - "):
        if desc.startswith(prefix):
            desc = desc[len(prefix):].lstrip()
            break
    # A sentence boundary is ". " followed by an uppercase letter — a bare
    # ". " split truncates legal citations mid-reference ("NIS2 Art. 21(2)").
    first = desc
    i = 0
    while (i := desc.find(". ", i)) != -1:
        nxt = desc[i + 2 : i + 3]
        if nxt.isupper():
            first = desc[:i]
            break
        i += 2
    first = first.rstrip(".")
    if len(first) > 140:
        first = first[:137].rstrip() + "…"
    return first or "(no description in source)"


def classify(slug: str) -> str:
    if any(slug.startswith(p) for p in REGULATION_PREFIXES):
        return REGULATORY_FAMILY
    for family, slugs in FAMILIES.items():
        if slug in slugs:
            return family
    return UNFILED


def maturity(doc: dict) -> str:
    """The playbook's Maturity-ladder tier, verbatim from the source.

    ``stable`` is the ladder's deployment-ready designation (see
    ROADMAP "Maturity ladder"); everything else is reported as the
    author wrote it. A missing field is surfaced loudly rather than
    defaulted — the schema requires it, so absence is a content bug
    the table should not paper over.
    """
    value = (doc.get("x_secops_ng") or {}).get("maturity")
    return value if isinstance(value, str) and value else "(unset!)"


def render(sources: dict[str, Path]) -> str:
    grouped: dict[str, list[str]] = {f: [] for f in FAMILIES}
    grouped[UNFILED] = []
    for slug in sorted(sources):
        grouped[classify(slug)].append(slug)

    docs = {slug: _load(src) for slug, src in sources.items()}
    tally: dict[str, int] = {}
    for doc in docs.values():
        tier = maturity(doc)
        tally[tier] = tally.get(tier, 0) + 1
    # Ladder order first, anything unexpected after, alphabetically.
    ladder = ("stable", "experimental", "draft", "deprecated")
    tally_text = " / ".join(
        f"{tally[t]} {t}" for t in
        (*[t for t in ladder if t in tally],
         *sorted(k for k in tally if k not in ladder))
    )

    lines: list[str] = [BEGIN, ""]
    total = sum(len(v) for v in grouped.values())
    lines.append(f"_{total} playbooks — {tally_text}. `stable` is the "
                 f"Maturity ladder's deployment-ready bar (ROADMAP § Maturity "
                 f"ladder). Regenerate with "
                 f"`python -m tools.render_playbook_table`; CI fails when this "
                 f"block is stale._")
    for family, slugs in grouped.items():
        if not slugs:
            continue
        lines += ["", f"### {family}", "",
                  "| Playbook | Maturity | What it does |", "|---|---|---|"]
        for slug in slugs:
            src = sources[slug]
            link = slug if src.parent != PLAYBOOK_DIR else "."
            doc = docs[slug]
            lines.append(f"| [`{slug}`]({link}/) | `{maturity(doc)}` "
                         f"| {short_description(doc)} |")
    lines += ["", END]
    return "\n".join(lines)


def apply(readme_text: str, table: str) -> str:
    try:
        head, rest = readme_text.split(BEGIN, 1)
        _, tail = rest.split(END, 1)
    except ValueError:
        raise SystemExit(
            f"markers not found in {README} — the README must contain the "
            f"begin/end comment pair for the generated block"
        )
    return head + table + tail


def main() -> int:
    sources = collect_sources()
    unfiled = [s for s in sorted(sources) if classify(s) == UNFILED]
    if unfiled:
        print(
            f"unfiled playbooks (add each to FAMILIES in {Path(__file__).name}): "
            + ", ".join(unfiled),
            file=sys.stderr,
        )
        # Render anyway — an Unfiled section in the output is honest, and the
        # test suite is what makes it a hard failure.
    current = README.read_text(encoding="utf-8")
    updated = apply(current, render(sources))
    if "--check" in sys.argv:
        if updated != current or unfiled:
            print("stale: regenerate with `python -m tools.render_playbook_table`",
                  file=sys.stderr)
            return 1
        print(f"fresh: {README.relative_to(REPO_ROOT)} matches {len(sources)} sources")
        return 0
    README.write_text(updated, encoding="utf-8")
    print(f"wrote {README.relative_to(REPO_ROOT)} ({len(sources)} playbooks)")
    return 1 if unfiled else 0


if __name__ == "__main__":
    raise SystemExit(main())
